# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_contrib <- function(Ck, yk, mk) {
    .Call(`_SurrogateParadoxTest_loglik_contrib`, Ck, yk, mk)
}

rbf_kernel <- function(x1, x2, length_scale, variance) {
    .Call(`_SurrogateParadoxTest_rbf_kernel`, x1, x2, length_scale, variance)
}

