// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loglik_contrib
double loglik_contrib(const arma::mat& Ck, const arma::vec& yk, const arma::vec& mk);
RcppExport SEXP _SurrogateParadoxTest_loglik_contrib(SEXP CkSEXP, SEXP ykSEXP, SEXP mkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Ck(CkSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type yk(ykSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mk(mkSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_contrib(Ck, yk, mk));
    return rcpp_result_gen;
END_RCPP
}
// rbf_kernel
arma::mat rbf_kernel(const arma::vec& x1, const arma::vec& x2, double length_scale, double variance);
RcppExport SEXP _SurrogateParadoxTest_rbf_kernel(SEXP x1SEXP, SEXP x2SEXP, SEXP length_scaleSEXP, SEXP varianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type variance(varianceSEXP);
    rcpp_result_gen = Rcpp::wrap(rbf_kernel(x1, x2, length_scale, variance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurrogateParadoxTest_loglik_contrib", (DL_FUNC) &_SurrogateParadoxTest_loglik_contrib, 3},
    {"_SurrogateParadoxTest_rbf_kernel", (DL_FUNC) &_SurrogateParadoxTest_rbf_kernel, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurrogateParadoxTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
